# ----------[ 2 ]----------

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the sum of the even-valued terms.

num = 2
previousNum = 1
sum = 0
while num < 4 * 10 ** 6:
    if num % 2 == 0:
        sum += num

    temp = num
    num += previousNum
    previousNum = temp
print(sum)
# 4613732
